name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release_zip_file:
    name: Publish HACS zip file asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compress Custom Component
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/zammad
          zip zammad.zip -r ./

      - uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: ${{ github.workspace }}/custom_components/zammad/zammad.zip